### ISSUE TITLE
Checkout fails with error 

### ISSUE THREAD

**Issue by DavideDelVecchio** [Azure-Samples/graphrag-legalcases-postgres#12]
git clone https://github.com/Azure-Samples/graphrag-legalcases-postgres.git
Cloning into 'graphrag-legalcases-postgres'...
remote: Enumerating objects: 876, done.
remote: Counting objects: 100% (317/317), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 876 (delta 127), reused 192 (delta 91), pack-reused 559 (from 1)
Receiving objects: 100% (876/876), 28.85 MiB | 8.09 MiB/s, done.
Resolving deltas: 100% (427/427), done.
error: invalid path 'scripts/load_python_env.sh:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by serdarmicrosoft** [comment]
Thanks for reporting the issue. It's resolved now. To fix your local clone, please run:  
```
rm -rf graphrag-legalcases-postgres  
git clone https://github.com/Azure-Samples/graphrag-legalcases-postgres.git
```
