### ISSUE TITLE
Git clone pulls empty repo

### ISSUE THREAD

**Issue by mazer-rakham** [Azure-Samples/graphrag-legalcases-postgres#14]
git clone, only pulls git folder, no repo items are included with it.

**Comment by mazer-rakham** [comment]
Looks like it is because of the .zoneidentifiers files, looks like windows is blocking the clone because of them

**Comment by serdarmicrosoft** [comment]
Thanks for reporting the issue! It's resolved now. To fix your local clone, please run:  
```
rm -rf graphrag-legalcases-postgres  
git clone https://github.com/Azure-Samples/graphrag-legalcases-postgres.git
```
