### ISSUE TITLE
User created with azd up in PostgresSql does not have superuser, making it hard to debug

### ISSUE THREAD

**Issue by mazer-rakham** [Azure-Samples/graphrag-legalcases-postgres#16]
![image](https://github.com/user-attachments/assets/e416413b-51f0-43a3-9216-87563719f999)

**Comment by serdarmicrosoft** [comment]
Thanks for the comment. We can configure it as a superuser, but in the meantime, you can use the admin user. You can find the admin username in the Security > Authentication section. To obtain a token, simply run the following command:
`az account get-access-token --resource https://ossrdbms-aad.database.windows.net`

**Comment by mazer-rakham** [comment]
Awesome thank you so much Serdar!
